# Generated by Django 4.0.1 on 2022-01-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_instructor',
        ),
        migrations.AddField(
            model_name='course',
            name='course_instructor',
            field=models.ManyToManyField(to='login.Instructor'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrolled_course',
        ),
        migrations.AddField(
            model_name='student',
            name='enrolled_course',
            field=models.ManyToManyField(to='login.Course'),
        ),
    ]
