# Generated by Django 4.0.1 on 2022-02-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_question_course_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
