# Generated by Django 4.0.1 on 2022-03-13 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_studentanswer'),
        ('login', '0006_remove_instructor_name_remove_instructor_password_and_more'),
    ]

    operations = [
    ]
