# Generated by Django 4.0.4 on 2022-04-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_remove_course_course_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.CharField(default='email@email.com', max_length=100),
        ),
        migrations.AddField(
            model_name='instructor',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='email@email.com', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
    ]
