# Generated by Django 3.2.10 on 2022-05-17 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_course_session_current_question'),
        ('login', '0011_alter_instructor_email_alter_student_email'),
    ]

    operations = [
    ]
